### PR TITLE
[13.0][IMP] add a created column

### PR DESCRIPTION
**Pull request by pierre-halleux**
Add an "Created" column that allows ordering objects
in a folder by `cmis:creationDate`.

### CODE REVIEW

**Comment by sbidoul** [comment]
@pierre-halleux @lmignon is this one ready to merge ?

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@sbidoul Yes it-is

**Comment by sbidoul** [comment]
Let's see. /ocabot merge patch

**Comment by sbidoul** [comment]
@lmignon the target branch is 13.0-dev. Can we change it to 13.0 ?

**Comment by sbidoul** [comment]
@pierre-halleux can you forward port to 14.0 ?

**Pull request merged**
