### PR TITLE
[12.0] next release

### PR DESCRIPTION
**Pull request by lmignon**
* [X] cmis_alf: Add method to support folder creation from space-tempalte

### CODE REVIEW

**Comment by sbidoul** [comment]
@lmignon it looks like the bot is looking at the status of github-pages: `Building a url from ('https://api.github.com', 'apps', 'github-pages')`. That one might not be green which could explain why the merge does not proceed. Where is that configured / visible in the GitHub UI?

**Comment by lmignon** [comment]
@sbidoul Thank you for the info... I don't know where to find this info. I'll take a look later...

**Comment by sbidoul** [comment]
Our DNS config for alfdoo.org was a bit outdated. I fixed that. Can you try again @lmignon ?

**Pull request closed without merging**
