### PR TITLE
[16.0] [FIX] CMIS Backend: form views

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
From https://github.com/OCA/connector-cmis/pull/45

### CODE REVIEW

**Comment by ThomasBinsfeld** [comment]
This is ready since https://github.com/OCA/connector-cmis/pull/45 is merged @lmignon

**Comment by lmignon** [comment]
@ThomasBinsfeld Can you rebase plz. Tests are :red_circle:

**Comment by ThomasBinsfeld** [comment]
I can't, it's already based on the latest version. Tests are red on the 16.0 branch.

**Comment by lmignon** [comment]
You could maybe find why so we can merge it...

**Review by FrancoMaxime — APPROVED** [review]

**Review by FrancoMaxime — APPROVED** [review]
LGTM. I've restarded the failed jobs. The pipeline was using an oldest version of cmis

**Pull request merged**
